package uiapp

import (
	"encoding/base64"

	"riftsync/assets"
)

func htmlDocument() string {
	brandIcon := base64.StdEncoding.EncodeToString(assets.RiftSyncIconPNG)
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>RiftSync</title>
<style>
:root {
  color-scheme:dark;
  --space-1:4px;--space-2:8px;--space-3:12px;--space-4:16px;--space-6:24px;--space-8:32px;
  --radius-sm:8px;--radius-md:12px;--radius-lg:16px;--blur:14px;
  --bg:#0b1118;--shell:#151d27;--glass:#17212c;--surface:#1b2632;--surface-hi:#253341;
  --well:#101821;--line:#405064;--line-soft:#2d3c4d;--ink:#f2f6fb;--muted:#aeb9c8;
  --cyan:#68d7d0;--blue:#829bf0;--green:#66dc93;--amber:#f0c36d;--red:#f0818b;
  --shadow:0 10px 28px #02060b66;--rail:64px;--side:244px;
}
*{box-sizing:border-box;scrollbar-width:none;-ms-overflow-style:none}
*::-webkit-scrollbar{display:none;width:0;height:0}
html,body{width:100%;height:100%;margin:0;overflow:hidden;background:var(--bg);color:var(--ink);font:14px/1.5 "Segoe UI",system-ui,sans-serif}
body{background-image:radial-gradient(circle at 18% 12%,#163447 0,transparent 34%),radial-gradient(circle at 88% 80%,#202a4a 0,transparent 30%)}
button,input,textarea{font:inherit}
button{min-height:40px;border:1px solid var(--line);border-radius:var(--radius-sm);padding:8px 14px;color:var(--ink);background:var(--surface-hi);box-shadow:none;cursor:pointer;font-weight:650;transition:background-color .16s ease,border-color .16s ease,color .16s ease,opacity .16s ease}
button:hover{border-color:#647991;background:#2d3d4d}button:active{background:#1f2b37}button:disabled{opacity:.45;cursor:not-allowed}
button.primary{color:#071716;border-color:var(--cyan);background:var(--cyan)}button.primary:hover{background:#87e5df}
button.danger{color:#ffe9eb;border-color:#96545c;background:#512d34}button.danger:hover{background:#63363e}
button.icon-button{width:40px;min-width:40px;padding:0}
button:focus-visible,input:focus-visible,textarea:focus-visible,.project-button:focus-visible,[tabindex]:focus-visible{outline:3px solid var(--cyan);outline-offset:2px}
input,textarea{width:100%;min-width:0;border:1px solid var(--line);border-radius:var(--radius-sm);background:var(--well);color:var(--ink);box-shadow:none;padding:10px 12px}
input:disabled,textarea:disabled{opacity:.6}textarea{resize:none;font:13px/1.55 Consolas,"Cascadia Mono",monospace}
.app{display:grid;grid-template-columns:var(--rail) minmax(0,1fr);grid-template-rows:64px minmax(0,1fr);width:100%;height:100%;overflow:hidden}
.app.sidebar-pinned{grid-template-columns:var(--side) minmax(0,1fr)}
.glass{background:var(--shell);border:1px solid var(--line-soft);box-shadow:var(--shadow)}
@supports ((backdrop-filter:blur(1px)) or (-webkit-backdrop-filter:blur(1px))){.glass,.panel,.modal,.sidebar{background:rgba(23,33,44,.84);backdrop-filter:blur(var(--blur));-webkit-backdrop-filter:blur(var(--blur))}}
.titlebar{grid-column:1/-1;display:flex;align-items:center;gap:var(--space-3);min-width:0;padding:var(--space-2) var(--space-3);border-width:0 0 1px;background:var(--shell);user-select:none;z-index:50}
.brand{display:flex;align-items:center;gap:var(--space-2);min-width:190px}.brand-logo{display:block;width:32px;height:32px;flex:0 0 32px;object-fit:contain}.brand strong{font-size:18px;letter-spacing:.2px}.brand small{display:block;color:var(--muted);font-size:10px;letter-spacing:.08em}
.title-context{display:flex;align-items:center;justify-content:center;gap:var(--space-2);min-width:0;flex:1}.title-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:750}.address{color:var(--muted);font:12px/1.5 Consolas,monospace}.state-text{color:var(--muted);font-size:12px;font-weight:700}
.lamp{width:10px;height:10px;flex:0 0 10px;border-radius:50%;background:var(--red)}.lamp.running{background:var(--green)}.lamp.starting{background:var(--amber)}.lamp.error{background:var(--red)}
.instance-actions,.window-actions{display:flex;align-items:center;gap:var(--space-2);flex-shrink:0}
.sidebar-wrap{position:relative;z-index:40;grid-row:2;min-width:0}.sidebar{position:absolute;inset:0 auto 0 0;width:var(--rail);display:flex;flex-direction:column;overflow:hidden;border-width:0 1px 0 0;background:var(--shell);transition:width .16s ease}
.sidebar-wrap:hover .sidebar,.sidebar-wrap:focus-within .sidebar,.sidebar-pinned .sidebar{width:var(--side)}
.sidebar-head{display:flex;align-items:center;gap:var(--space-3);height:56px;padding:var(--space-2) var(--space-3);white-space:nowrap;border-bottom:1px solid var(--line-soft)}.sidebar-head strong{opacity:0;transition:opacity .12s}.sidebar-wrap:hover .sidebar-head strong,.sidebar-wrap:focus-within .sidebar-head strong,.sidebar-pinned .sidebar-head strong{opacity:1}
.project-list{flex:1;min-height:0;overflow-y:auto;overflow-x:hidden;padding:var(--space-2)}
.project-button{position:relative;display:grid;grid-template-columns:40px 0;justify-content:center;align-items:center;gap:0;width:100%;min-width:0;margin-bottom:var(--space-2);padding:4px;border:1px solid transparent;border-radius:var(--radius-md);background:transparent;color:var(--ink);text-align:left;cursor:pointer}
.sidebar-wrap:hover .project-button,.sidebar-wrap:focus-within .project-button,.sidebar-pinned .project-button{grid-template-columns:40px minmax(0,1fr);justify-content:stretch;gap:var(--space-2)}
.project-button:hover{background:#253241;border-color:var(--line-soft)}.project-button.active{background:#293847;border-color:#567086}.project-button.active:before{content:"";position:absolute;left:-5px;width:3px;height:24px;border-radius:3px;background:var(--cyan)}
.avatar{position:relative;display:grid;place-items:center;width:40px;height:40px;border-radius:var(--radius-sm);background:var(--avatar,#49607d);font-weight:850}.avatar .lamp{position:absolute;right:-2px;bottom:-2px;border:2px solid var(--surface);width:11px;height:11px}
.project-copy{min-width:0;opacity:0;transition:opacity .12s}.sidebar-wrap:hover .project-copy,.sidebar-wrap:focus-within .project-copy,.sidebar-pinned .project-copy{opacity:1}.project-copy strong,.project-copy span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.project-copy span{color:var(--muted);font-size:12px}
.sidebar-foot{display:grid;gap:var(--space-2);padding:var(--space-2)}.side-action{display:grid;grid-template-columns:46px minmax(0,1fr);align-items:center;gap:0;width:100%;padding:0;overflow:hidden}.side-icon{display:grid;place-items:center;width:46px;height:38px;line-height:1}.side-icon svg{display:block;width:16px;height:16px}.side-action .action-label{min-width:0;padding-right:var(--space-2);opacity:0;white-space:nowrap;text-align:center}.sidebar-wrap:hover .action-label,.sidebar-wrap:focus-within .action-label,.sidebar-pinned .action-label{opacity:1}
.sidebar-wrap.force-collapsed .sidebar{width:var(--rail);transition:none}.sidebar-wrap.force-collapsed .project-button{grid-template-columns:40px 0;justify-content:center;gap:0}.sidebar-wrap.force-collapsed .sidebar-head strong,.sidebar-wrap.force-collapsed .project-copy,.sidebar-wrap.force-collapsed .action-label{opacity:0}
.workspace{grid-column:2;grid-row:2;min-width:0;min-height:0;display:grid;grid-template-rows:56px minmax(0,1fr);overflow:hidden}.toolbar{display:flex;align-items:end;min-width:0;padding:var(--space-2) var(--space-4) 0;border-bottom:1px solid var(--line-soft);background:#111a23cc}.tabs{display:flex;gap:var(--space-1);min-width:0;overflow-x:auto}.tab{min-width:96px;border-color:transparent;border-radius:var(--radius-sm) var(--radius-sm) 0 0;background:transparent;color:var(--muted)}.tab:hover{background:#253241}.tab.active{color:var(--cyan);background:#1d2935;border-color:var(--line-soft);border-bottom-color:transparent}
.content{min-width:0;min-height:0;overflow:hidden;padding:var(--space-4)}.panel-page{display:none;width:100%;height:100%;min-width:0;min-height:0;overflow:hidden}.panel-page.active{display:block}
.panel{min-width:0;min-height:0;border:1px solid var(--line-soft);border-radius:var(--radius-md);background:var(--glass);box-shadow:var(--shadow);padding:var(--space-4);overflow:hidden}.panel h2{margin:0 0 var(--space-1);font-size:16px}.label{color:var(--muted);font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.hint{color:var(--muted);font-size:12px;overflow-wrap:anywhere}.value{margin-top:var(--space-1);font-size:22px;font-weight:800;overflow-wrap:anywhere}
.overview{display:grid;grid-template-rows:auto auto minmax(0,1fr);gap:var(--space-3);height:100%;min-height:0;overflow:auto}.summary-card{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:start;gap:var(--space-4)}.project-name{margin:var(--space-2) 0 var(--space-1);font-size:24px;font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.path{font:12px/1.5 Consolas,monospace;color:#d0d8e4;overflow-wrap:anywhere}.summary-state{display:grid;grid-template-columns:10px auto;align-items:center;justify-self:start;gap:var(--space-2);min-height:46px;padding:6px 10px;border:1px solid var(--line-soft);border-radius:var(--radius-sm);background:var(--surface);white-space:nowrap}.summary-state strong{display:block;font-size:14px;line-height:1.2}.summary-state .hint{margin-top:2px;line-height:1.2}.summary-activity{grid-column:1/-1;display:grid;grid-template-columns:96px minmax(0,1fr);gap:var(--space-3);padding-top:var(--space-3);border-top:1px solid var(--line-soft)}
.metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--space-3)}.metric{min-width:0;padding:var(--space-4);border:1px solid var(--line-soft);border-radius:var(--radius-md);background:var(--surface);box-shadow:none}.button-row{display:flex;flex-wrap:wrap;gap:var(--space-2);margin-top:var(--space-4)}
.disclosure{width:100%;align-self:stretch}.disclosure-trigger{display:flex;align-items:center;justify-content:space-between;width:100%;padding:0;border:0;background:transparent;text-align:left}.disclosure-trigger>span:first-child{display:flex;align-items:baseline;flex-wrap:wrap;gap:var(--space-2);min-width:0}.disclosure-trigger:hover{background:transparent;color:var(--cyan)}.disclosure-trigger:after{content:"+";font-size:20px}.disclosure-trigger[aria-expanded="true"]:after{content:"−"}.disclosure-body{padding-top:var(--space-4)}.disclosure-body[hidden]{display:none}.health-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--space-2)}.health-cell{min-width:0;border:1px solid var(--line-soft);border-radius:var(--radius-sm);background:var(--well);padding:var(--space-3)}.health-cell .value{font-size:18px}.truncate{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.error{color:#ffb6bc}
.history-shell{display:grid;grid-template-columns:minmax(220px,.36fr) minmax(0,1fr);gap:var(--space-3);height:100%;min-height:0}.history-list,.history-detail{min-height:0;overflow:auto}.history-item{width:100%;min-width:0;text-align:left;margin-bottom:var(--space-2);background:var(--surface)}.history-item span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.history-item small{color:var(--muted)}.change-row{min-width:0;padding:var(--space-3) 0;border-bottom:1px solid var(--line-soft)}.change-row div{color:var(--muted);font-size:12px;overflow-wrap:anywhere}
.exec-shell{display:grid;grid-template-columns:minmax(330px,.9fr) minmax(360px,1.1fr);gap:var(--space-3);height:100%;min-height:0}.exec-editor{display:grid;grid-template-rows:auto auto minmax(120px,1fr) auto;gap:var(--space-3)}.exec-result{display:grid;grid-template-rows:auto minmax(100px,1fr) auto minmax(118px,.72fr);gap:var(--space-2)}.token-row,.input-button{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:var(--space-2)}.exec-toolbar{display:grid;grid-template-columns:100px minmax(0,1fr) auto auto;align-items:end;gap:var(--space-2)}.output,.code-view{min-width:0;min-height:0;margin:0;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid var(--line-soft);border-radius:var(--radius-sm);background:#0a1118;color:#c8f5df;padding:var(--space-3);font:13px/1.55 Consolas,monospace}
.recent-head{display:flex;align-items:center;justify-content:space-between;gap:var(--space-2)}.exec-history{min-width:0;min-height:0;overflow-y:auto;overflow-x:hidden;border:1px solid var(--line-soft);border-radius:var(--radius-sm);background:var(--well);padding:var(--space-1)}.exec-history-item{display:grid;grid-template-columns:minmax(0,1fr) auto auto;align-items:center;gap:var(--space-2);min-width:0;padding:var(--space-2);border-bottom:1px solid var(--line-soft)}.exec-history-item:last-child{border:0}.exec-history-item button{min-height:36px}.exec-history-copy{min-width:0}.exec-history-title,.exec-history-meta{display:block;max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.exec-history-title{font-weight:750}.exec-history-meta{color:var(--muted);font-size:12px}
.config-shell{display:grid;grid-template-columns:minmax(0,1fr) minmax(280px,.72fr);gap:var(--space-3);height:100%;min-height:0;overflow:auto}.form-panel{overflow:auto}.field{min-width:0;margin-top:var(--space-3)}.field label{display:block;margin-bottom:var(--space-1)}.form-grid{display:grid;grid-template-columns:minmax(0,1fr) 140px;gap:var(--space-3)}.toggle-row{display:flex;justify-content:space-between;align-items:center;gap:var(--space-3);padding:var(--space-3);border:1px solid var(--line-soft);border-radius:var(--radius-sm);background:var(--well)}.toggle-row>span{display:flex;align-items:baseline;flex-wrap:wrap;gap:var(--space-2);min-width:0}.toggle-row input{width:20px;height:20px}.config-side{display:flex;flex-direction:column;align-items:stretch;gap:var(--space-3)}.config-side .panel{width:100%;overflow:visible}.danger-zone{border-color:#70434a}
.empty{display:grid;place-items:center;min-height:100px;color:var(--muted);text-align:center;padding:var(--space-6)}
.modal-backdrop{position:fixed;inset:0;z-index:200;display:none;place-items:center;padding:var(--space-6);background:#050a10c7}.modal-backdrop.open{display:grid}.modal{width:min(780px,100%);max-height:min(680px,90vh);display:grid;grid-template-rows:auto minmax(0,1fr);gap:var(--space-3);border:1px solid var(--line);border-radius:var(--radius-lg);background:var(--shell);box-shadow:0 24px 70px #000b;padding:var(--space-4)}.modal-head{display:flex;align-items:center;justify-content:space-between;gap:var(--space-3)}.modal-head h2{font-size:20px}.modal-body{min-height:0;overflow:auto}.modal-actions{display:flex;gap:var(--space-2)}.meta-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--space-2);margin-bottom:var(--space-3)}.meta-cell{min-width:0;padding:var(--space-2);border:1px solid var(--line-soft);border-radius:var(--radius-sm);background:var(--well);overflow-wrap:anywhere}.add-form{display:grid;gap:var(--space-3);min-width:0}.toast{position:fixed;right:var(--space-4);bottom:var(--space-4);z-index:300;max-width:min(420px,80vw);display:none;padding:var(--space-3) var(--space-4);border:1px solid #8d5259;border-radius:var(--radius-sm);background:#452a30;color:#ffe4e7;box-shadow:var(--shadow)}.toast.open{display:block}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media(max-width:980px){.brand small,.title-context .address{display:none}.health-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.history-shell,.exec-shell,.config-shell{grid-template-columns:1fr}.history-shell,.exec-shell,.config-shell{overflow:auto}.exec-editor,.exec-result{min-height:430px}.instance-actions .optional{display:none}}
@media(max-width:680px){.brand{min-width:auto}.brand div{display:none}.state-text{display:none}.metrics{grid-template-columns:1fr}.summary-card{grid-template-columns:1fr}.exec-toolbar,.form-grid{grid-template-columns:1fr}.content{padding:var(--space-2)}.tab{min-width:82px}.meta-grid,.health-grid{grid-template-columns:1fr}.instance-actions button{padding-inline:9px}.summary-activity{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
</style>
</head>
<body>
<div id="app" class="app">
  <header id="appHeader" class="titlebar glass">
    <div class="brand"><img class="brand-logo" src="data:image/png;base64,` + brandIcon + `" alt="" aria-hidden="true"><div><strong>RiftSync</strong><small>ROBLOX STUDIO LIVE SYNC</small></div></div>
    <div class="title-context" aria-live="polite"><span id="titleLamp" class="lamp" aria-hidden="true"></span><span id="titleName" class="title-name">No project</span><span id="titleState" class="state-text">Stopped</span><span id="titleAddress" class="address">—</span></div>
    <div class="instance-actions" aria-label="Selected project actions"><button id="logsBtn" class="optional">Logs</button><button id="startBtn" class="primary">Start</button><button id="stopBtn">Stop</button></div>
    <div class="window-actions"><button id="minimizeBtn" class="icon-button" aria-label="Minimize window">—</button><button id="closeBtn" class="icon-button danger" aria-label="Close RiftSync">×</button></div>
  </header>
  <aside class="sidebar-wrap">
    <nav class="sidebar glass" aria-label="Projects">
      <div class="sidebar-head"><button id="pinBtn" class="icon-button" title="Pin sidebar" aria-label="Pin project sidebar" aria-expanded="false">☰</button><strong>Projects</strong></div>
      <div id="projectList" class="project-list"></div>
      <div class="sidebar-foot">
        <button id="startAllBtn" class="side-action"><span class="side-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M8 5.5v13l10-6.5z"/></svg></span><span class="action-label">Start All</span></button>
        <button id="addProjectBtn" class="side-action primary"><span class="side-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" d="M12 5v14M5 12h14"/></svg></span><span class="action-label">Add Project</span></button>
      </div>
    </nav>
  </aside>
  <main class="workspace" aria-label="Selected project workspace">
    <div class="toolbar">
      <div class="tabs" role="tablist" aria-label="Project workspace">
        <button id="overviewTab" class="tab active" role="tab" aria-controls="overviewPanel" aria-selected="true" tabindex="0" data-panel="overviewPanel">Overview</button>
        <button id="historyTab" class="tab" role="tab" aria-controls="historyPanel" aria-selected="false" tabindex="-1" data-panel="historyPanel">History</button>
        <button id="execTab" class="tab" role="tab" aria-controls="execPanel" aria-selected="false" tabindex="-1" data-panel="execPanel">Exec</button>
        <button id="configTab" class="tab" role="tab" aria-controls="configPanel" aria-selected="false" tabindex="-1" data-panel="configPanel">Config</button>
      </div>
    </div>
    <div class="content">
      <section id="overviewPanel" class="panel-page active" role="tabpanel" aria-labelledby="overviewTab" tabindex="0">
        <div class="overview">
          <article id="workspacePanel" class="panel summary-card"><div><div class="label">Active project</div><h1 id="projectNameText" class="project-name">No project</h1><div id="projectPathText" class="path">—</div><div class="button-row"><button id="openBtn">Open Folder</button><button id="changePathBtn">Edit Settings</button></div></div><div class="summary-state"><span id="overviewLamp" class="lamp" aria-hidden="true"></span><div><strong id="overviewStatusText">Stopped</strong><div id="uptimeText" class="hint">Not running</div></div></div><div class="summary-activity"><div class="label">Last activity</div><div><div id="activityText" class="truncate">No Studio activity yet.</div><div id="activityHint" class="hint"></div><div id="errorText" class="hint error" role="alert"></div></div></div></article>
          <div id="metricStrip" class="metrics" aria-label="Project metrics">
            <div class="metric"><div class="label">Revision</div><div id="revisionText" class="value">0</div><div id="modeText" class="hint">Live sync</div></div>
            <div class="metric"><div class="label">Indexed</div><div id="indexedText" class="value">0</div><div id="indexedHint" class="hint">0 scripts · 0 UI</div></div>
            <div class="metric"><div class="label">Git</div><div id="gitText" class="value">Pending</div><div class="hint">Project history</div></div>
          </div>
          <article id="healthPanel" class="panel disclosure"><button id="diagnosticsToggle" class="disclosure-trigger" aria-expanded="false" aria-controls="diagnosticsBody"><span><span class="label">Diagnostics</span><span class="hint">Connection and watcher details</span></span><span class="sr-only">Toggle diagnostics</span></button><div id="diagnosticsBody" class="disclosure-body" hidden><div class="health-grid">
            <div class="health-cell"><div class="label">Studio polls</div><div id="pollsText" class="value">0</div></div>
            <div class="health-cell"><div class="label">App requests</div><div id="requestsText" class="value">0</div></div>
            <div class="health-cell"><div class="label">Watcher</div><div id="healthModeText" class="value">Live</div></div>
            <div class="health-cell"><div class="label">Last scan</div><div id="lastScanText" class="value">Ready</div></div>
          </div></div></article>
        </div>
      </section>
      <section id="historyPanel" class="panel-page" role="tabpanel" aria-labelledby="historyTab" tabindex="0" hidden>
        <div class="history-shell"><aside class="panel history-list"><div class="recent-head"><div><h2>Revisions</h2><div class="hint">Selected project only</div></div><button id="historyRefreshBtn">Refresh</button></div><div id="historyTimeline"><div class="empty">No revisions yet.</div></div></aside><article class="panel history-detail"><div id="revisionSummary" class="hint">Choose a revision.</div><div id="historyDetail"></div></article></div>
      </section>
      <section id="execPanel" class="panel-page" role="tabpanel" aria-labelledby="execTab" tabindex="0" hidden>
        <div class="exec-shell">
          <article class="panel exec-editor"><div><h2>Remote Exec</h2><div class="hint">Runs only through the selected project.</div></div><div><label class="label" for="execTokenDisplay">Project token</label><div class="token-row"><input id="execTokenDisplay" readonly><button id="execTokenCopyBtn">Copy</button></div><div id="execTokenHint" class="hint"></div></div><label class="sr-only" for="execSourceInput">Luau source</label><textarea id="execSourceInput" spellcheck="false" placeholder="print(workspace.Name)"></textarea><div class="exec-toolbar"><div><label class="label" for="execTimeoutInput">Timeout</label><input id="execTimeoutInput" type="number" min="1" max="120" value="10"></div><div id="execStatusText" class="hint" role="status" aria-live="polite">Start project and enable Exec in Studio.</div><button id="execLatestBtn">Latest</button><button id="execRunBtn" class="primary">Run</button></div></article>
          <article class="panel exec-result"><div><h2>Result</h2><div id="execResultHint" class="hint">Ready.</div></div><pre id="execOutputText" class="output">Ready.</pre><div class="recent-head"><div><div class="label">Recent commands</div><div id="execHistoryHint" class="hint">Per-project history</div></div><button id="execHistoryRefreshBtn">Refresh</button></div><div id="execHistoryList" class="exec-history"><div class="empty">No commands yet.</div></div></article>
        </div>
      </section>
      <section id="configPanel" class="panel-page" role="tabpanel" aria-labelledby="configTab" tabindex="0" hidden>
        <div class="config-shell"><article id="configPathPanel" class="panel form-panel"><h2>Project</h2><div class="hint">Identity and local folder for this instance.</div><div class="field"><label class="label" for="instanceNameInput">Display name</label><div class="input-button"><input id="instanceNameInput"><button id="renameBtn">Rename</button></div></div><div class="field"><label class="label" for="syncRootInput">Sync root</label><div class="input-button"><input id="syncRootInput"><button id="syncRootPickerBtn">Choose</button></div></div><div class="button-row"><button id="applyConfigBtn" class="primary">Save Settings</button><button id="configOpenBtn">Open Folder</button></div><div id="configApplyStatus" class="hint" role="status" aria-live="polite">Saved</div></article><aside class="config-side"><article id="serverSettingsPanel" class="panel"><h2>Connection</h2><div class="hint">Use a unique port for each project, then copy its token into Studio.</div><div class="form-grid"><div class="field"><label class="label" for="hostInput">Host</label><input id="hostInput"></div><div class="field"><label class="label" for="portInput">Port</label><input id="portInput" inputmode="numeric"></div></div><div id="connectionSummary" class="path" style="margin-top:12px">—</div></article><article class="panel disclosure"><button id="advancedToggle" class="disclosure-trigger" aria-expanded="false" aria-controls="advancedBody"><span><span class="label">Advanced</span><span class="hint">Config path and debug mode</span></span><span class="sr-only">Toggle advanced settings</span></button><div id="advancedBody" class="disclosure-body" hidden><div class="field"><label class="label" for="configInput">Config path</label><input id="configInput" readonly></div><div class="field toggle-row"><span><strong>Debug mode</strong><span class="hint">Extra runtime diagnostics</span></span><input id="debugInput" type="checkbox" aria-label="Debug mode"></div></div></article><article class="panel danger-zone"><h2>Remove project</h2><div class="hint">Only remove this project from RiftSync. Files and configuration remain untouched.</div><div class="button-row"><button id="removeProjectBtn" class="danger">Remove Project</button></div></article></aside></div>
      </section>
    </div>
  </main>
</div>
<div id="viewModal" class="modal-backdrop" aria-hidden="true"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="viewTitle" tabindex="-1"><header class="modal-head"><div><h2 id="viewTitle" style="margin:0">Command details</h2><div id="viewSubtitle" class="hint"></div></div><div class="modal-actions"><button id="viewCopyBtn">Copy Source</button><button id="viewCloseBtn">Close</button></div></header><div class="modal-body"><div id="viewMeta" class="meta-grid"></div><div class="label">Source</div><pre id="viewSource" class="code-view" style="min-height:180px"></pre><div class="label" style="margin-top:12px">Last result</div><pre id="viewResult" class="code-view" style="min-height:90px"></pre></div></section></div>
<div id="addModal" class="modal-backdrop" aria-hidden="true"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="addTitle" tabindex="-1" style="width:min(560px,100%)"><header class="modal-head"><div><h2 id="addTitle" style="margin:0">Add project</h2><div class="hint">Import an existing config or create a local-only config.</div></div><button id="addCloseBtn">Close</button></header><div class="modal-body add-form"><div><label class="label" for="addNameInput">Display name (optional)</label><input id="addNameInput"></div><div><label class="label" for="addRootInput">Sync root</label><div class="input-button"><input id="addRootInput"><button id="addPickBtn">Choose</button></div></div><div><label class="label" for="addConfigInput">Existing config path (optional)</label><input id="addConfigInput" placeholder="Leave empty to use .rblxsync\\sync_config.json"></div><button id="addCreateBtn" class="primary">Add Project</button><div id="addStatus" class="hint" role="status" aria-live="polite"></div></div></section></div>
<div id="logsModal" class="modal-backdrop" aria-hidden="true"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="logsTitle" tabindex="-1"><header class="modal-head"><div><h2 id="logsTitle" style="margin:0">Project logs</h2><div class="hint">Selected project only</div></div><div class="modal-actions"><button id="refreshLogsBtn">Refresh</button><button id="closeLogsBtn">Close</button></div></header><pre id="logsText" class="code-view"></pre></section></div>
<div id="toast" class="toast" role="status" aria-live="polite"></div>
<script>
const $=id=>document.getElementById(id);
let instances=[],selectedId="",latest=null,execHistory=[],selectedEntry=null,busy=false,modalReturnFocus=null;
const scopedPaths=new Set(["/app/status","/app/start","/app/stop","/app/restart","/app/config/apply","/app/open-folder","/app/pick-folder","/app/history","/app/exec/history","/app/exec/run","/app/exec/rerun","/app/logs"]);
function withInstance(path){const scoped=[...scopedPaths].some(base=>path===base||path.startsWith(base+"?"));if(!scoped||!selectedId)return path;return path+(path.includes("?")?"&":"?")+"instance_id="+encodeURIComponent(selectedId)}
async function api(path,options){const response=await fetch(withInstance(path),options);const text=await response.text();let body={};try{body=JSON.parse(text)}catch(_){throw new Error(text||"Invalid response")}if(!response.ok||body.status==="error")throw new Error(body.error||body.message||("HTTP "+response.status));return body}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
function hashColor(value){let h=0;for(const c of String(value))h=(h*31+c.charCodeAt(0))>>>0;const colors=["#49607d","#58607f","#3e716c","#71556c","#75633f","#4d6d56"];return colors[h%colors.length]}
function initials(name){const bits=String(name||"?").trim().split(/\s+/);return(bits.length>1?bits[0][0]+bits[bits.length-1][0]:bits[0].slice(0,2)).toUpperCase()}
function toast(message){const node=$("toast");node.textContent=message;node.classList.add("open");clearTimeout(node._timer);node._timer=setTimeout(()=>node.classList.remove("open"),3500)}
function current(){return instances.find(item=>item.id===selectedId)||null}
function lampClass(app){return app&&app.running?"running":app&&app.starting?"starting":app&&app.last_error?"error":"stopped"}
function renderSidebar(body){instances=body.instances||[];selectedId=body.selected_instance_id||instances[0]?.id||"";const pinned=!!body.sidebar_pinned;$("app").classList.toggle("sidebar-pinned",pinned);if(pinned)sidebarWrap.classList.remove("force-collapsed");$("pinBtn").textContent=pinned?"⇤":"☰";$("pinBtn").setAttribute("aria-expanded",String(pinned));$("pinBtn").setAttribute("aria-label",pinned?"Unpin project sidebar":"Pin project sidebar");$("projectList").innerHTML=instances.length?instances.map(item=>{const a=item.app||{},active=item.id===selectedId,status=a.status||"Stopped";return '<button class="project-button '+(active?"active":"")+'" data-id="'+escapeHtml(item.id)+'" aria-current="'+(active?"page":"false")+'" aria-label="'+escapeHtml(item.name+", "+status+", port "+(a.port||"not set"))+'"><span class="avatar" style="--avatar:'+hashColor(item.id)+'">'+escapeHtml(initials(item.name))+'<span class="lamp '+lampClass(a)+'" aria-hidden="true"></span></span><span class="project-copy"><strong>'+escapeHtml(item.name)+'</strong><span>'+escapeHtml(status)+' · '+escapeHtml(a.port||"—")+'</span></span></button>'}).join(""):'<div class="empty">Add your first project.</div>';$("projectList").querySelectorAll("[data-id]").forEach(node=>node.onclick=()=>selectInstance(node.dataset.id));if(body.warning)toast(body.warning)}
async function loadInstances(renderSelected=true){try{const body=await api("/app/instances");renderSidebar(body);if(renderSelected)await refreshSelected()}catch(err){toast(err.message)}}
async function selectInstance(id){if(id===selectedId)return;await api("/app/instances/select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});selectedId=id;execHistory=[];await loadInstances(true);await loadHistory();await loadExecHistory()}
function setDisabled(noProject){["startBtn","stopBtn","logsBtn","openBtn","changePathBtn","historyRefreshBtn","execRunBtn","execLatestBtn","execHistoryRefreshBtn","execTokenCopyBtn","applyConfigBtn","renameBtn","removeProjectBtn"].forEach(id=>$(id).disabled=noProject||busy)}
function render(app){latest=app||null;const item=current();if(!app||!item){$("titleName").textContent="No project";$("titleState").textContent="Stopped";$("titleAddress").textContent="—";$("titleLamp").className="lamp stopped";$("overviewLamp").className="lamp stopped";$("projectNameText").textContent="No project";setDisabled(true);return}setDisabled(false);const stateClass=lampClass(app);$("titleName").textContent=item.name;$("titleState").textContent=app.status||"Stopped";$("titleAddress").textContent=app.address||"—";$("titleLamp").className="lamp "+stateClass;$("overviewLamp").className="lamp "+stateClass;$("overviewStatusText").textContent=app.status;$("uptimeText").textContent=app.uptime?"Up "+app.uptime:"Not running";$("revisionText").textContent=app.revision||0;$("modeText").textContent=app.mode||"Live sync";$("indexedText").textContent=app.indexed||0;$("indexedHint").textContent=(app.scripts||0)+" scripts · "+(app.ui||0)+" UI";$("gitText").textContent=app.git_status||"Pending";$("projectNameText").textContent=item.name;$("projectPathText").textContent=app.sync_root||"—";$("pollsText").textContent=app.polls||0;$("requestsText").textContent=app.request_count||0;$("healthModeText").textContent=app.mode||"Live";$("lastScanText").textContent=app.indexed?(app.indexed+" items"):"Ready";$("activityText").textContent=app.activity_text||"No Studio activity yet.";$("activityHint").textContent=[app.activity_operation,app.activity_progress?app.activity_progress+"%":"",app.activity_revision?"rev "+app.activity_revision:""].filter(Boolean).join(" · ");$("errorText").textContent=app.last_error||"";$("startBtn").disabled=busy||app.running||app.starting;$("stopBtn").disabled=busy||!app.running;$("execTokenDisplay").value=app.remote_exec_token||"";$("execTokenHint").textContent=app.remote_exec_available?"Copy token into the selected Studio profile.":"Remote Exec will be prepared when the project starts.";$("instanceNameInput").value=item.name;$("syncRootInput").value=app.sync_root||"";$("configInput").value=item.config_path||app.config_path||"";$("hostInput").value=app.host||"127.0.0.1";$("portInput").value=app.port||8765;$("debugInput").checked=!!app.debug;$("connectionSummary").textContent=(app.host||"127.0.0.1")+":"+(app.port||8765);const locked=app.running||app.starting;["syncRootInput","syncRootPickerBtn","hostInput","portInput","debugInput","applyConfigBtn"].forEach(id=>$(id).disabled=locked||busy);$("configApplyStatus").textContent=locked?"Stop this project before editing settings.":"Ready to edit."}
async function refreshSelected(){if(!selectedId){render(null);return}try{const body=await api("/app/status");render(body.app)}catch(err){toast(err.message)}}
async function action(path){if(!selectedId)return;busy=true;render(latest);try{const body=await api(path,{method:"POST"});if(body.app)render(body.app);await loadInstances(false)}catch(err){toast(err.message)}finally{busy=false;await refreshSelected()}}
function setPanel(id,focus=false){document.querySelectorAll(".tab").forEach(t=>{const active=t.dataset.panel===id;t.classList.toggle("active",active);t.setAttribute("aria-selected",String(active));t.tabIndex=active?0:-1;if(active&&focus)t.focus()});document.querySelectorAll(".panel-page").forEach(p=>{const active=p.id===id;p.classList.toggle("active",active);p.hidden=!active});if(id==="historyPanel")loadHistory();if(id==="execPanel")loadExecHistory()}
function setDisclosure(buttonId,bodyId,open){const button=$(buttonId),body=$(bodyId);button.setAttribute("aria-expanded",String(open));body.hidden=!open}
function openModal(id,trigger=document.activeElement){const node=$(id);modalReturnFocus=trigger;$("app").setAttribute("aria-hidden","true");$("app").inert=true;node.classList.add("open");node.setAttribute("aria-hidden","false");const target=node.querySelector("button,input,textarea,[tabindex]:not([tabindex='-1'])")||node.querySelector(".modal");target?.focus()}
function closeModal(id){const node=$(id);node.classList.remove("open");node.setAttribute("aria-hidden","true");$("app").removeAttribute("aria-hidden");$("app").inert=false;if(modalReturnFocus&&document.contains(modalReturnFocus))modalReturnFocus.focus();modalReturnFocus=null}
async function loadHistory(){if(!selectedId)return;try{const body=await api("/app/history");const rows=body.revisions||[];$("historyTimeline").innerHTML=rows.length?rows.map(r=>'<button class="history-item" data-rev="'+r.rev+'"><span>Revision '+r.rev+'</span><small>'+escapeHtml(r.change_count||0)+' changes'+(r.git_commit_short?" · "+escapeHtml(r.git_commit_short):"")+'</small></button>').join(""):'<div class="empty">No revisions yet.</div>';$("historyTimeline").querySelectorAll("[data-rev]").forEach(n=>n.onclick=()=>loadRevision(n.dataset.rev))}catch(err){$("historyTimeline").innerHTML='<div class="empty">'+escapeHtml(err.message)+'</div>'}}
async function loadRevision(rev){try{const body=await api("/app/history?rev="+encodeURIComponent(rev));const changes=body.changes||[];$("revisionSummary").textContent="Revision "+rev+" · "+(body.change_count||0)+" changes · Git "+(body.git_commit_short||"—");$("historyDetail").innerHTML=changes.length?changes.map(c=>'<div class="change-row"><strong>'+escapeHtml(c.op||"upsert")+' · '+escapeHtml(c.entity||"item")+'</strong><div>'+escapeHtml(c.rbx_path||c.new_rbx_path||c.local_path||"—")+'</div><div>'+escapeHtml(c.local_path||"")+'</div></div>').join(""):'<div class="empty">No detail.</div>'}catch(err){toast(err.message)}}
function formatEntry(entry){const s=entry.source_summary||{};const title=s.first_line||String(entry.source||"").split(/\r?\n/).find(Boolean)||"(empty)";return{title,status:(entry.ok?"ok":entry.result_state||"error")+" · "+(entry.timeout_sec||0)+"s"}}
function renderExecHistory(){const list=$("execHistoryList");list.innerHTML=execHistory.length?execHistory.slice(0,30).map(entry=>{const f=formatEntry(entry);return '<div class="exec-history-item"><div class="exec-history-copy"><span class="exec-history-title" title="'+escapeHtml(f.title)+'">'+escapeHtml(f.title)+'</span><span class="exec-history-meta">'+escapeHtml(entry.submitted_by||"—")+' · '+escapeHtml(f.status)+'</span></div><button data-view="'+escapeHtml(entry.id)+'">View</button><button data-run="'+escapeHtml(entry.id)+'">Run</button></div>'}).join(""):'<div class="empty">No Remote Exec history yet.</div>';list.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>viewEntry(b.dataset.view));list.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>rerunExec(b.dataset.run))}
async function loadExecHistory(){if(!selectedId)return;try{const body=await api("/app/exec/history");execHistory=body.entries||[];$("execHistoryHint").textContent=body.warning||"Stored in this project's .rblxsync";renderExecHistory()}catch(err){$("execHistoryList").innerHTML='<div class="empty">'+escapeHtml(err.message)+'</div>'}}
function viewEntry(id){selectedEntry=execHistory.find(e=>e.id===id);if(!selectedEntry)return;const e=selectedEntry;const f=formatEntry(e);$("viewSubtitle").textContent=f.title;$("viewMeta").innerHTML=[["Status",e.result_state||"—"],["Submitted",e.submitted_by||"—"],["Timeout",(e.timeout_sec||0)+"s"],["Lines",e.source_summary?.line_count||0],["Duration",e.duration_ms?e.duration_ms+"ms":"—"],["Timestamp",e.timestamp?new Date(e.timestamp).toLocaleString():"—"]].map(x=>'<div class="meta-cell"><div class="label">'+escapeHtml(x[0])+'</div><div>'+escapeHtml(x[1])+'</div></div>').join("");$("viewSource").textContent=e.source||"";$("viewResult").textContent=e.output||e.traceback||e.error||"No stored output for this history entry.";openModal("viewModal")}
async function runExec(){const source=$("execSourceInput").value;if(!source.trim()){toast("Source is required.");return}setExecBusy(true);try{const body=await api("/app/exec/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source,timeout_sec:Number($("execTimeoutInput").value)||0})});renderExecResult(body);await loadExecHistory()}catch(err){$("execOutputText").textContent=err.message;$("execResultHint").textContent="Remote Exec failed"}finally{setExecBusy(false)}}
async function rerunExec(id){setExecBusy(true);try{const body=await api("/app/exec/rerun",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:id||"",timeout_sec:Number($("execTimeoutInput").value)||0})});renderExecResult(body);await loadExecHistory()}catch(err){$("execOutputText").textContent=err.message;$("execResultHint").textContent="Remote Exec failed"}finally{setExecBusy(false)}}
function renderExecResult(body){$("execOutputText").textContent=body.output||"";const r=body.result||{};$("execResultHint").textContent="state="+(r.state||"—")+" · ok="+!!r.ok+(r.duration_ms?" · "+r.duration_ms+"ms":"")}
function setExecBusy(value){busy=value;["execRunBtn","execLatestBtn","execHistoryRefreshBtn"].forEach(id=>$(id).disabled=value);$("execStatusText").textContent=value?"Running command...":"Start project and enable Exec in Studio."}
async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch(_){const a=document.createElement("textarea");a.value=text;a.style.position="fixed";a.style.left="-9999px";document.body.appendChild(a);a.select();let ok=false;try{ok=document.execCommand("copy")}catch(_){}a.remove();return ok}}
async function saveConfig(){if(!latest||latest.running)return;try{const payload={config_path:$("configInput").value,sync_root:$("syncRootInput").value,host:$("hostInput").value,port:$("portInput").value,git_enabled:true,debug:$("debugInput").checked,legacy_scan:false};const body=await api("/app/config/apply",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});render(body.app);$("configApplyStatus").textContent="Saved";await loadInstances(false)}catch(err){$("configApplyStatus").textContent=err.message;toast(err.message)}}
async function renameProject(){const name=$("instanceNameInput").value.trim();if(!name)return;try{await api("/app/instances/update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selectedId,name})});await loadInstances(true)}catch(err){toast(err.message)}}
async function removeProject(){if(!selectedId||!confirm("Remove this project from RiftSync? Files and config will stay on disk."))return;try{const body=await api("/app/instances/remove",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selectedId})});renderSidebar(body);await refreshSelected()}catch(err){toast(err.message)}}
async function addProject(){const payload={name:$("addNameInput").value,sync_root:$("addRootInput").value,config_path:$("addConfigInput").value};$("addStatus").textContent="Adding...";try{const body=await api("/app/instances",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});renderSidebar(body);closeModal("addModal");$("addNameInput").value="";$("addRootInput").value="";$("addConfigInput").value="";await refreshSelected()}catch(err){$("addStatus").textContent=err.message}}
async function pickNewFolder(){try{const body=await api("/app/instances/pick-folder",{method:"POST"});if(body.selected)$("addRootInput").value=body.path}catch(err){toast(err.message)}}
async function pickConfigFolder(){try{const body=await api("/app/pick-folder",{method:"POST"});if(body.selected)$("syncRootInput").value=body.path}catch(err){toast(err.message)}}
async function startAll(){busy=true;try{await api("/app/start-all",{method:"POST"});await loadInstances(true)}catch(err){toast(err.message)}finally{busy=false}}
function formatLogs(body){const lines=["RiftSync project log","revision="+(body.revision||0)+" running="+!!body.running,""];(body.scan_warnings||[]).forEach(w=>lines.push("[warning] "+w));(body.events||[]).forEach(e=>lines.push("["+new Date((e.ts||0)*1000).toLocaleTimeString()+"] "+e.kind+"  "+e.message));return lines.join("\n")}
async function loadLogs(){try{$("logsText").textContent=formatLogs(await api("/app/logs"))}catch(err){$("logsText").textContent=err.message}}
document.querySelectorAll(".tab").forEach(t=>{t.onclick=()=>setPanel(t.dataset.panel);t.onkeydown=e=>{const tabs=[...document.querySelectorAll(".tab")],index=tabs.indexOf(t);let next=index;if(e.key==="ArrowRight")next=(index+1)%tabs.length;else if(e.key==="ArrowLeft")next=(index-1+tabs.length)%tabs.length;else if(e.key==="Home")next=0;else if(e.key==="End")next=tabs.length-1;else return;e.preventDefault();setPanel(tabs[next].dataset.panel,true)}});
$("appHeader").onmousedown=e=>{if(!e.target.closest("button,input")&&window.appDragWindow)window.appDragWindow()};
$("minimizeBtn").onclick=e=>{e.stopPropagation();if(window.appMinimizeWindow)window.appMinimizeWindow()};
$("closeBtn").onclick=e=>{e.stopPropagation();fetch("/app/window/close",{method:"POST",keepalive:true}).catch(()=>{});if(window.appCloseWindow)window.appCloseWindow()};
const sidebarWrap=document.querySelector(".sidebar-wrap");
$("pinBtn").onclick=async()=>{const pinned=!$("app").classList.contains("sidebar-pinned");$("app").classList.toggle("sidebar-pinned",pinned);sidebarWrap.classList.toggle("force-collapsed",!pinned);$("pinBtn").textContent=pinned?"⇤":"☰";$("pinBtn").setAttribute("aria-expanded",String(pinned));$("pinBtn").setAttribute("aria-label",pinned?"Unpin project sidebar":"Pin project sidebar");if(!pinned){$("pinBtn").blur();document.querySelector(".tab.active")?.focus()}await api("/app/sidebar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pinned})})};
sidebarWrap.addEventListener("mouseleave",()=>sidebarWrap.classList.remove("force-collapsed"));sidebarWrap.addEventListener("focusin",()=>{if(!$("app").classList.contains("sidebar-pinned"))sidebarWrap.classList.remove("force-collapsed")});
$("startBtn").onclick=()=>action("/app/start");$("stopBtn").onclick=()=>action("/app/stop");$("startAllBtn").onclick=startAll;$("openBtn").onclick=()=>action("/app/open-folder");$("configOpenBtn").onclick=()=>action("/app/open-folder");$("changePathBtn").onclick=()=>setPanel("configPanel");
$("historyRefreshBtn").onclick=loadHistory;$("execHistoryRefreshBtn").onclick=loadExecHistory;$("execRunBtn").onclick=runExec;$("execLatestBtn").onclick=()=>rerunExec("");$("execTokenCopyBtn").onclick=()=>copyText($("execTokenDisplay").value).then(ok=>toast(ok?"Token copied.":"Copy failed."));
$("applyConfigBtn").onclick=saveConfig;$("renameBtn").onclick=renameProject;$("removeProjectBtn").onclick=removeProject;$("syncRootPickerBtn").onclick=pickConfigFolder;
$("diagnosticsToggle").onclick=()=>setDisclosure("diagnosticsToggle","diagnosticsBody",$("diagnosticsToggle").getAttribute("aria-expanded")!=="true");$("advancedToggle").onclick=()=>setDisclosure("advancedToggle","advancedBody",$("advancedToggle").getAttribute("aria-expanded")!=="true");
$("addProjectBtn").onclick=e=>openModal("addModal",e.currentTarget);$("addCloseBtn").onclick=()=>closeModal("addModal");$("addPickBtn").onclick=pickNewFolder;$("addCreateBtn").onclick=addProject;
$("viewCloseBtn").onclick=()=>closeModal("viewModal");$("viewCopyBtn").onclick=()=>copyText(selectedEntry?.source||"").then(ok=>toast(ok?"Source copied.":"Copy failed."));
$("logsBtn").onclick=e=>{openModal("logsModal",e.currentTarget);loadLogs()};$("closeLogsBtn").onclick=()=>closeModal("logsModal");$("refreshLogsBtn").onclick=loadLogs;
["viewModal","addModal","logsModal"].forEach(id=>$(id).onclick=e=>{if(e.target.id===id)closeModal(id)});
document.addEventListener("keydown",e=>{const modal=document.querySelector(".modal-backdrop.open");if(!modal)return;if(e.key==="Escape"){e.preventDefault();closeModal(modal.id);return}if(e.key!=="Tab")return;const focusable=[...modal.querySelectorAll("button:not(:disabled),input:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex='-1'])")].filter(node=>node.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
async function boot(){await loadInstances(true);await loadHistory();await loadExecHistory();setInterval(async()=>{await loadInstances(false);await refreshSelected()},1200)}
boot();
</script>
</body>
</html>`
}
